name: generate synced google package repository

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
env:
  ARCHIVE: https://developers.google.com/unity/archive
concurrency: generate-synced-repository
jobs:
  generate-synced-repository:
    runs-on: ubuntu-latest
    steps:
      - name: generate synced google package repository
        run: |
          set -e
          packages=$(curl -sS https://developers.google.com/unity/archive | grep -o 'com.google[^<]*' | cut -d'/' -f1 | grep -v '^com$' | sort -u)
          echo $packages
          for package in $packages; do
            if gh repo view RageAgainstThePixel/$package >/dev/null 2>&1; then
              continue
            fi

            echo "Creating repository for $package"
            gh repo create RageAgainstThePixel/$package --public --template RageAgainstThePixel/com.google.external-dependency-manager

            # Poll for the workflow file to be available
            for i in {1..10}
            do
              echo "Checking if workflow file is available ($i/10)..."
              if gh workflow view upm-sync.yaml -R RageAgainstThePixel/$package > /dev/null 2>&1
              then
                  echo "Workflow file is available, running workflow..."
                  gh workflow run upm-sync.yaml -R RageAgainstThePixel/$package
                  break
              else
                  echo "Workflow file is not available yet, waiting..."
                  sleep 5
              fi
            done
          done
        env:
          GH_TOKEN: ${{ secrets.CI_TOKEN }}
